language: python
python:
  - "2.7"

install:
  - "python setup.py install"

virtualenv:
  system_site_packages: true

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq libblas-dev"
  - "sudo apt-get install -qq liblapack-dev"
#   - "sudo apt-get install -qq python-pandas"

script: py.test

notifications:
  email: false
